### ISSUE TITLE
How to deploy this project in Kubernetes?

### ISSUE THREAD

**Issue by linjinjin123** [FudanSELab/train-ticket#10]
Is there any easy way to deploy the whole project on Kubernetes? 
Such as the Sock-shop: https://github.com/microservices-demo/microservices-demo/blob/master/deploy/kubernetes/complete-demo.yaml

**Comment by jichaofdu** [comment]
I add a directory named _K8S_ in _Document_ in _Master Branch_.
The _ReadMe.md_ in that directory may be helpful.
Thank you very much!
