### ISSUE TITLE
系统laod test脚本

### ISSUE THREAD

**Issue by Lizhi-Liao** [FudanSELab/train-ticket#101]
你好，我想load test贵团队开发的系统，请问哪里可以找到load test的脚本呢，比如jmeter script这种的。

谢谢！

**Comment by Lizhi-Liao** [comment]
@flyer1212 
@zhongyuanzhao000

**Comment by zhongyuanzhao000** [comment]
你好，目前train ticket暂时还没有 load test脚本，谢谢您的提醒！
