### ISSUE TITLE
There is a potential runtime exception

### ISSUE THREAD

**Issue by Liloveyang** [FudanSELab/train-ticket#103]
Hello,

First of all i want to thank you for sharing your code.
But when I was operating some of my files, there was a runtime exception.

I found that java.lang.NullPointerException was thrown by the conveterObject method in ts-common/src/edu.fudan.common.util.JsonUtils.java,When the object2Json method is abnormal, the jsonContent object is returned as null, and then passed to the json2Object object, an error occurs.

```
public class TsTest {
    public static void main(String[] args) {
        TsTest.conveterObject(null,String.class);
    }

    public static String object2Json(Object obj) {
        String result = null;
        try {
            ObjectMapper objectMapper = new ObjectMapper();
            result = objectMapper.writeValueAsString(obj);
        } catch (IOException e) {

        }
        return result;
    }

    public static <T> T json2Object(String json, Class<T> cls) {
        T result = null;
        try {
            ObjectMapper objectMapper = new ObjectMapper();
            result = objectMapper.readValue(json, cls);
        } catch (IOException e) {

        }
        return result;
    }

    public static <T> T conveterObject(Object srcObject, Class<T> destObjectType) {
        String jsonContent = object2Json(srcObject);
        return json2Object(null, destObjectType);
    }
}
```

so I suggest you add catch or throw to the source code An exception goes out, which is convenient for the caller to develop.

Thank you!

**Comment by zhongyuanzhao000** [comment]
Thank you for your issue! 
Your advice is useful! 
And we will fix it soon！
