### ISSUE TITLE
jaeger

### ISSUE THREAD

**Issue by jingfenmg** [FudanSELab/train-ticket#104]
这些微服务怎么集成到jaeger上的，

**Comment by LeBW** [comment]
我们使用 [java-spring-jaeger](https://github.com/opentracing-contrib/java-spring-jaeger) 进行自动化的 instrumentation 。

**Comment by jingfenmg** [comment]
我想把这微服务在SkyWalking展示链路，该如何操作那

**Comment by LeBW** [comment]
> 我想把这微服务在SkyWalking展示链路，该如何操作那

Skywalking Server是符合 Opentracing 规范的。Jaeger client 也是符合 Opentracing 规范的，只需将 client 端的发送URL 设置为 server端相应API接口即可。

**Comment by jingfenmg** [comment]
这个订票系统有几十个小的服务，怎么指定url，还有该怎么指定 Skywalking-agent.jar

**Comment by LeBW** [comment]
具体做法请参阅相关文档。
