### ISSUE TITLE
登陆密码错误

### ISSUE THREAD

**Issue by jingfenmg** [FudanSELab/train-ticket#105]
pod都是running状态登陆时
![image](https://user-images.githubusercontent.com/53138344/77994099-079aea80-735c-11ea-93cc-fa6380b2b77b.png)

**Comment by jingfenmg** [comment]
没人回复吗

**Comment by zhongyuanzhao000** [comment]
您好，建议尝试重启一下与ts-auth-service以及user-service相关的几个pod，看是否有效

**Comment by jingfenmg** [comment]
想问一个每个服务都是单独的数据库吗，mongo的口令是什么

**Comment by zhongyuanzhao000** [comment]
对的，每个业务服务都是单独的数据库。

**Comment by jingfenmg** [comment]
每个业务的数据库口令是什么，在那里找

**Comment by jingfenmg** [comment]
可以通过客户端连接mongo数据库吗，还是在容器内查看

**Comment by zhongyuanzhao000** [comment]
你好，业务数据库的口令在每个服务的资源目录yaml文件中；mongo数据库可以进入容器查看，也可以尝试用客户端连接。

**Comment by jingfenmg** [comment]
能麻烦您把账号密码错误相关那几个服务例举一下，重新部署一下

**Comment by jingfenmg** [comment]
我只看到了mysql的密码是root，没看到mongo的口令

**Comment by zhongyuanzhao000** [comment]
应该是 ts-auth-service、ts-user-service、ts-verification-code-service这几个服务

**Comment by jingfenmg** [comment]
好的，mongodb口令我们要知道吗，还是就是在容器中看就可以了

**Comment by zhongyuanzhao000** [comment]
目前应该不用知道，不影响使用

**Comment by jingfenmg** [comment]
我没看到咱们这个服务挂载数据卷，数据是存在数据库中，那数据库的pods挂了怎么办

**Comment by zhongyuanzhao000** [comment]
有一个可以将数据持久化的部署版本，利用PV/PVC实现，在deployment/quickstart-k8s-mongo-persistence目录下。

**Comment by jingfenmg** [comment]
我在k8s上面部署了skywalking,想看一下train-ticket的链路调用情况，有什么建议吗

**Comment by vslidan** [comment]
@zhongyuanzhao000 你好，方面留一个联系方式吗？我们是CSTC的，希望能和您进一步交流下

**Comment by zhongyuanzhao000** [comment]
@jingfenmg Train Ticket已经植入了 Jaeger，也可以使用Jaeger查看链路调用情况。 skywalking目前不太了解。

**Comment by jingfenmg** [comment]
好，还想问一下，就是单独的一个服务创建会失败吗，我拿出一个单独的在新的ns下创建是失败的

**Comment by zhongyuanzhao000** [comment]
抱歉，目前还没有尝试过单独部署一个服务。

**Comment by zhongyuanzhao000** [comment]
@vslidan 欢迎使用邮箱联系，我的邮箱：19210240209@fudan.edu.cn

**Comment by jingfenmg** [comment]
好的，谢谢您，我这个普通用户登录为啥会经常失败啊，是访问的人数限制吗，还是有什么其他的限制，

**Comment by zhongyuanzhao000** [comment]
应该没有这方面的限制。这种一直登录失败的情况我也没遇到过。如果实在不行，重新部署所有pod也可以试一试，按照部署文件的顺序，等数据库pod部署成功完毕，再部署服务pod，然后ui。。。

**Comment by LeBW** [comment]
1. 我们已经集成了Jaeger作为链路追踪系统，一般情况下已经足够使用。如果仍想使用Skywalking来观察链路情况，可以参考Skywalking的[这个文档](https://github.com/apache/skywalking/blob/v7.0.0/docs/en/setup/backend/backend-receivers.md)，其中说明了如何在Skywalking中使用Jaeger Receiver，当然，这样功能是有限的。如果想完全发挥Skywalking的分析能力，还是使用原生的Skywalking埋点方式比较好，可以参考使用Skywalking 的字节码增强探针。
2. 多数服务是无法单独创建的，你看一下log信息应该就能发现问题了，一般都是无法找到数据库之类的错误。
3. 登陆失败，请使用Jaeger观察相关链路情况，查找错误原因，一般都是某个服务响应出问题了。

**Comment by jingfenmg** [comment]
ts-inside-payment-service这个服务显示running，实际没运行起来，健康检查没通过，端口连接不上，该怎么解决

**Comment by jingfenmg** [comment]
目前是可以了，重新部署好多遍

**Comment by jingfenmg** [comment]
最近有很多pod启动失败，describe查看连不上端口

**Comment by jingfenmg** [comment]
是内存不够还是什么原因

**Comment by jingfenmg** [comment]
/train-ticket/deployment/quickstart-k8s-mongo-persistence
用的这个yml文件部署的
