### ISSUE TITLE
quickstart-docker-compose后无法正常使用

### ISSUE THREAD

**Issue by Butter934** [FudanSELab/train-ticket#112]
十分感谢你们将此系统开源！我在进行quickstart-docker-compose的时候遇到了一些问题：
请问使用quickstart-docker-compose后，访问本地8080端口后，出现这样的界面，除了有个界面外其他的功能几乎完全使用不了。点击右上admin登录也出现undefined错误。  
请问这是我构建时出了问题还是说使用quickstart-docker-compose.yml构建就只是展示个界面呢？

![图片](https://user-images.githubusercontent.com/42533108/86510415-f9101380-be21-11ea-9da4-33e5326d8c04.png)
![图片](https://user-images.githubusercontent.com/42533108/86510564-5193e080-be23-11ea-8c6a-580329cf60a4.png)
（尝试进入其他功能模块时也只是提示要先登录）

**Comment by zhongyuanzhao000** [comment]
您好，这应该部署的时候，与验证码相关的服务没有部署成功导致的，建议重新部署一遍试试
