### ISSUE TITLE
When buying a ticket, an email is sent to 163.com

### ISSUE THREAD

**Issue by ajanes** [FudanSELab/train-ticket#113]
Hi,
I installed train-ticket using docker compose on one of our servers. When I start it, log-in, I click on "Ticket Reserve", I click on "Search", I choose the first ticket, I click on "Booking", I select the first contact, I click on "Select" and then I click on "Submit"

The program gets stuck in a never ending loop. I checked the code; maybe it is because its trying to send a confirmation email to an account on 163.com? How can I deactivate this?

Thanks!

**Comment by zhongyuanzhao000** [comment]
Hello, if you want to deactivate sending email service, you can follow the steps below:

1. Find the file:'ts-preserve-service/src/main/java/preserve/service/PreserveServiceImpl.java', and then comment out the code at line 237 ( ie  // sendEmail(notifyInfo, headers); ).
2. Also find the file:'ts-preserve-other-service/src/main/java/preserveOther/service/PreserveOtherServiceImpl.java', comment out the line 241 code.
3. Rebuild the docker image of'ts-preserve-service' and'ts-preserve-other-service', and then replace the old image in the deployment file.

**Comment by ajanes** [comment]
Thanks for the quick reply! 

I tried to execute the instructions to rebuild the docker image:

# 1. clone the repository
git clone https://github.com/FudanSELab/train-ticket.git
cd train-ticket
# 2. build the application
mvn clean package -Dmaven.test.skip=true
# 3. build the docker images
docker-compose build

At step 2 I get the following error:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-jar-plugin:2.6:jar (default-jar) on project ts-common: Execution default-jar of goal org.apache.maven.plugins:maven-jar-plugin:2.6:jar failed: An API incompatibility was encountered while executing org.apache.maven.plugins:maven-jar-plugin:2.6:jar: java.lang.ExceptionInInitializerError: null
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.apache.maven.plugins:maven-jar-plugin:2.6
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/Users/ajanes/.m2/repository/org/apache/maven/plugins/maven-jar-plugin/2.6/maven-jar-plugin-2.6.jar
[ERROR] urls[1] = file:/Users/ajanes/.m2/repository/org/slf4j/slf4j-jdk14/1.5.6/slf4j-jdk14-1.5.6.jar
[ERROR] urls[2] = file:/Users/ajanes/.m2/repository/org/slf4j/jcl-over-slf4j/1.5.6/jcl-over-slf4j-1.5.6.jar
[ERROR] urls[3] = file:/Users/ajanes/.m2/repository/org/apache/maven/reporting/maven-reporting-api/2.2.1/maven-reporting-api-2.2.1.jar
[ERROR] urls[4] = file:/Users/ajanes/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.1/doxia-sink-api-1.1.jar
[ERROR] urls[5] = file:/Users/ajanes/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.1/doxia-logging-api-1.1.jar
[ERROR] urls[6] = file:/Users/ajanes/.m2/repository/junit/junit/3.8.1/junit-3.8.1.jar
[ERROR] urls[7] = file:/Users/ajanes/.m2/repository/commons-cli/commons-cli/1.2/commons-cli-1.2.jar
[ERROR] urls[8] = file:/Users/ajanes/.m2/repository/org/codehaus/plexus/plexus-interactivity-api/1.0-alpha-4/plexus-interactivity-api-1.0-alpha-4.jar
[ERROR] urls[9] = file:/Users/ajanes/.m2/repository/backport-util-concurrent/backport-util-concurrent/3.1/backport-util-concurrent-3.1.jar
[ERROR] urls[10] = file:/Users/ajanes/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar
[ERROR] urls[11] = file:/Users/ajanes/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
[ERROR] urls[12] = file:/Users/ajanes/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.11/plexus-interpolation-1.11.jar
[ERROR] urls[13] = file:/Users/ajanes/.m2/repository/org/apache/maven/maven-archiver/2.6/maven-archiver-2.6.jar
[ERROR] urls[14] = file:/Users/ajanes/.m2/repository/org/apache/maven/shared/maven-shared-utils/0.7/maven-shared-utils-0.7.jar
[ERROR] urls[15] = file:/Users/ajanes/.m2/repository/com/google/code/findbugs/jsr305/2.0.1/jsr305-2.0.1.jar
[ERROR] urls[16] = file:/Users/ajanes/.m2/repository/org/codehaus/plexus/plexus-utils/3.0.20/plexus-utils-3.0.20.jar
[ERROR] urls[17] = file:/Users/ajanes/.m2/repository/org/codehaus/plexus/plexus-archiver/2.9/plexus-archiver-2.9.jar
[ERROR] urls[18] = file:/Users/ajanes/.m2/repository/org/codehaus/plexus/plexus-io/2.4/plexus-io-2.4.jar
[ERROR] urls[19] = file:/Users/ajanes/.m2/repository/commons-io/commons-io/2.2/commons-io-2.2.jar
[ERROR] urls[20] = file:/Users/ajanes/.m2/repository/org/apache/commons/commons-compress/1.9/commons-compress-1.9.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR] 
[ERROR] -----------------------------------------------------

**Comment by zhongyuanzhao000** [comment]
hi, this API incompatibility is related to the version of the Maven plugin, perhaps you can try to tweak it.

**Comment by LillyWu** [comment]
I got the same issue and it fails my load test. 
```
2021-03-10` 18:15:23 ERROR n.service.NotificationServiceImpl - Failed to close server connection after message failures; nested exception is javax.mail.MessagingException: Can't send command to SMTP host;

  nested exception is:
	java.net.SocketException: Connection closed by remote host. Failed messages: com.sun.mail.smtp.SMTPSendFailedException: 554 MI:STC 163 smtp1,GdxpCgDHhQ43nEhgW3efBw--.1655S2 1615371322,601,please see http://mail.163.com/help/help_spam_16.htm?ip=35.228.207.255&hostid=smtp1&time=1615371322
```
Is it possible for your team to provide the images directly?

**Comment by kagaya85** [comment]
Hi, This problem is caused by this line of function [sendEmail](https://github.com/FudanSELab/train-ticket/blob/6da7af034d9c56a118cc7d7a54e905539e7daeeb/ts-preserve-service/src/main/java/preserve/service/PreserveServiceImpl.java#L235) function (also in `PreserveOtherServiceImpl`), try to comment out these function and rebuild, then replace the image url in docker-compose or k8s yaml.

**Comment by LillyWu** [comment]
Hi @kagaya85, thanks a lot for your fast resposne. 
I followed the instruction above, but it failed. Actually, for someone who is not familiar with your code, it has a high probability to fail the build. 

So could you help build the images? and provide the images directly for us.

**Comment by LillyWu** [comment]
@kagaya85 Could you kindly tell me when the new images will be ready?  Thanks.

**Comment by kagaya85** [comment]
The image on dcoker hub will not be updated in recent time, you need to rebuild it yourself, here is a python script may help you. [build_upload_image](https://github.com/FudanSELab/train-ticket/blob/skywalking/build_upload_image.py)


-------- 原始邮件 --------
发件人： LillyWu ***@***.***>
日期： 2021年3月12日周五 16:31
收件人： FudanSELab/train-ticket ***@***.***>
抄送： Kagaya ***@***.***>, Mention ***@***.***>
主 题： Re: [FudanSELab/train-ticket] When buying a ticket, an email is sent to 163.com (#113)

@kagaya85<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkagaya85&data=04%7C01%7C%7Cb849ced34f9f4e5cd80b08d8e53129da%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637511346609454291%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=7%2Bc9S0XPaS2oTDOmLSRtMUAMVpug4qeV7hUJrNS%2Fvqo%3D&reserved=0> Could you kindly tell me when the new images will be ready? Thanks.

―

**Comment by LillyWu** [comment]
@kagaya85  Thanks for your reply.  I tried the script to build the images. The error is the same which is expected (and also docker hub authentication issue). 

```
[ERROR] Failed to execute goal on project ts-service: Could not resolve dependencies for project org.services:ts-service:pom:0.1.0: Failed to collect dependencies at org.springframework.boot:spring-boot-starter-integration:jar:1.5.22.RELEASE -> org.springframework.integration:spring-integration-core:jar:4.3.21.RELEASE -> org.springframework:spring-messaging:jar:4.3.25.RELEASE: Failed to read artifact descriptor for org.springframework:spring-messaging:jar:4.3.25.RELEASE: Could not transfer artifact org.springframework:spring-messaging:pom:4.3.25.RELEASE from/to central (https://repo.maven.apache.org/maven2): /home/li/.m2/repository/org/springframework/spring-messaging/4.3.25.RELEASE/spring-messaging-4.3.25.RELEASE.pom.part.lock (No such file or directory) -> [Help 1]
```
As I mentioned before, it is difficult for someone who is not familiar with your development stacks to build the image. That's why I am here asking for help, which is the same for the creator of this issue. 
If it's not time-consuming for you, please help build the three images that your fix affects.  Thx.

**Comment by Humbertzhang** [comment]
If you have trouble in maven, please GOOGLE it. 
I googled your problem, and i find some stackoverflow questions about it: [stackoverflow](https://stackoverflow.com/questions/41979802/gradle-could-not-resolve-org-springframework-bootspring-boot-gradle-plugin1-4) It seems that you have some network problems, so that you can't download packages, please check your network or proxy seetings.

And, Maven, Docker and Kubernetes are the most common technology stacks, There are many resources about it. If your are not familiar with it, please study it.

For build scripts, kagaya haven provided one for you, But your question is about maven, not about scripts. If you can't set up your maven, no scripts will help you. 

Of course We can build images for you, but we can't do that for everyone of every branches, right?

**Comment by LillyWu** [comment]
@Humbertzhang I would say it's impressive that you responded in a quick manner.  But I feel being unrespected, particularly, @LeBW adds  `+1` to your reply. I am here asking for help and also provide the details about the potential solutions. It's totally fine to tell that you cannot support it as it's out of your scope. But I don't think you need to tell ppl how to do! I have knowledge of docker, Kubernetes for 5-6 years. 

The reason I point out the issue of the script  https://github.com/FudanSELab/train-ticket/blob/skywalking/build_upload_image.py is that it has issues. It requires setting the environment variables and also the prefix is hard-coded, it won't work for someone who uses different repo in docker-hub. 

We all are creating a harmonious open-source environment. Here is a code-of-conduct that you may want to read: https://microsoft.github.io/codeofconduct/

**Comment by kagaya85** [comment]
@LillyWu Sorry, we don't think that build image is a problem for a trained developer, If you think it's confused, we also provided script in `/hack`, try it by follows:

* editing some account info in `hack/pushimg.sh`
* run `mvn clean package`
* using `bash hack/pushimg.sh`
 
I have tried to build and did not reproduce your problems.

This is a closed issue, if it doesn't solve your problem, please open a new issue and try to describe in detail the problems you have encountered and the attempts you have made.

Good luck!
