### ISSUE TITLE
Base64 for password/secret management

### ISSUE THREAD

**Issue by akondasif** [FudanSELab/train-ticket#115]
Greetings,

We are researchers and we are looking for insecure coding patterns and configurations in the microservice architecture repositories. In your repository, we have found instances of BASE64 usage. CWE says "A programmer can attempt to remedy the password management problem by obscuring the password with an encoding function, such as base 64 encoding, but this effort does not adequately protect the password."

Hopefully, you agree and will fix it.

Source: 

https://github.com/FudanSELab/train-ticket/blob/a4ed2433b0b6ab6e0d60115fc19efecb2548c6cd/ts-auth-service/src/main/java/auth/security/jwt/JWTProvider.java#L26

**Comment by akondasif** [comment]
Another instance is here: 

https://github.com/FudanSELab/train-ticket/blob/a4ed2433b0b6ab6e0d60115fc19efecb2548c6cd/ts-common/src/main/java/edu/fudan/common/security/jwt/JWTUtil.java#L30

**Comment by zhongyuanzhao000** [comment]
Thank you for your reminding. We will consider it carefully.
Or, do you have a good way to fix it?

**Comment by akondasif** [comment]
Can try `BCryptPasswordEncoder ` https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/crypto/bcrypt/BCryptPasswordEncoder.html

**Comment by akondasif** [comment]
We also provided some fixes for insecure HTTP endpoints in https://github.com/FudanSELab/train-ticket/pull/114
