### ISSUE TITLE
Are there public image for the project in docker hub

### ISSUE THREAD

**Issue by JackGzj** [FudanSELab/train-ticket#12]
I trid to deploy the project and found that you build a private image repositories in your k8s, I can not find any related images in docker hub either using the image in "docker-compose.yml". And I want to ask if there are public images of the project. Or I need to build all images by the dockerfile?

**Comment by jichaofdu** [comment]
Sorry, we tried to push these images to docker hub but the speed is very slow and finally we gave up.
I will try again at 2018-07-26 to upload our images.
We deployed an private docker registry  in out lab. You may search this document for more details about  [docker registry](https://docs.docker.com/registry/#what-it-is). 
You may reference [Readme.md](https://github.com/microcosmx/train_ticket/blob/master/Document/k8s/ReadMe.md) for more details about building images. 
Thank you very much!

**Comment by JackGzj** [comment]
Oh, thank you for your answer. I read the document and I wonder if I need to build every image by entering the service directory (I am building them for k8s) or any other way.

**Comment by jichaofdu** [comment]
No, you do not need to do that.
You just use the cmd "docker-compose build", and docker-compose will help you build all images automatically.
Thx!

**Comment by linjinjin123** [comment]
I have built all the images and uploaded to the dockerhub
https://cloud.docker.com/u/jinjinlin/repository/list
