### ISSUE TITLE
API Requests

### ISSUE THREAD

**Issue by rajibhossen** [FudanSELab/train-ticket#133]
### What would you like to be added
API Documentation.

### Why is this needed
To Create own load Testing/testing microservices

### Additional context
I want to use API requests. Made a post request to this endpoint "/api/v1/users/login" with the following payload  {"username": "fdse_microservice", "password": "111111"}. It throws error 400, message":"JSON parse error: Unrecognized token 'username': was expecting ('true', 'false' or 'null');

I'm not sure what fields should I use or not. Any help will be appreciated. thanks.

**Comment by ajanes** [comment]
Hi Rajib! We created a tool (https://github.com/pptam/pptam-tool) that uses locust.io to do load test on the trainticket application! Contact me if you want to try it out! We use 2 machines, one to drive the load test, one to setup trainticket. We deploy train ticket using docker, perform the load test using locust.io, and then collect the data. If you are just interested in the API calls, have a look at https://github.com/pptam/pptam-tool/blob/master/design_trainticket/locustfile.py!

**Comment by rajibhossen** [comment]
Thank you very much. That's what I was looking for. I also need to do the load test and very much interested to try your system. I deployed Train Ticket in the K8S cluster.

**Comment by ajanes** [comment]
You can have a look at https://github.com/pptam/pptam-tool/blob/master/installation/Installation_full.md and try to install it. Probably something will not work since we are still working on this framework - then drop me a mail at ajanes@unibz.it :)

**Comment by ajanes** [comment]
Well - if you *just* want to do a load test on an already deployed installation, then our setup is *much* easier... I'll add this point to our documentation!

**Comment by rajibhossen** [comment]
Your tools are great. I'll try the load test first. If I face any issues, I have your email. :).  "I'll add this point to our documentation!" - that would be wonderful.
