### ISSUE TITLE
Enable volume mount in some microservices for providing the possibility to inject anomalies to filesystem 

### ISSUE THREAD

**Issue by LillyWu** [FudanSELab/train-ticket#135]
### What would you like to be added
I would like to inject different types of anomalies to train-ticket, including filesystem. But I found none of the microservices mount any files some the host, which fails my anomaly injection. 

### Why is this needed
Enrich anomaly injection experiments

**Comment by Humbertzhang** [comment]
We do not currently have this plan, you can implement this feature yourself, and we welcome your PR!
