### ISSUE TITLE
consider setting COMPOSE_HTTP_TIMEOUT to a higher value

### ISSUE THREAD

**Issue by donydex** [FudanSELab/train-ticket#14]
Hi,chao,
there is a problem when i try the Clustering runtime environment(docker swarm) step:
when i try:
`docker-compose up`
it reported:
`ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).`
And i try to:
`COMPOSE_HTTP_TIMEOUT=200 docker-compose up`
But it doesn't work and report:
`If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 200).
`

**Comment by ManuelOverdijk** [comment]
Same issue, any news on this?

**Comment by LeBW** [comment]
> Same issue, any news on this?

Do you use docker swarm to deploy the application? I’m sorry but we it’s not been supported now.
