### ISSUE TITLE
The service cannot be started, the web page cannot be opened

### ISSUE THREAD

**Issue by XuGuanghui6688** [FudanSELab/train-ticket#140]
I set up 4 Ubuntu servers, a master node and three child nodes, installed jdk1.18, maven version 3.6.3, docker version 19.03.8, installed kubelet, kubectl, and kubeadm are all 1.18.0 versions, the k8s cluster has been deployed, and then quickly start the trainticket system, but there are always services that cannot be started correctly, as shown in the figure below, the main page of Trainticket cannot be opened correctly, is it because I am using the Ubuntu server or the reason for the installed version, or other reasons? Do I need to re-deploy the system on the Centos system?
![服务没有全部启动问题](https://user-images.githubusercontent.com/81084175/111904348-7b5c6880-8a81-11eb-879f-5c3c509ad37a.png)

**Comment by kagaya85** [comment]
Hi @XuGuanghui6688 , I don't think it has anything to do with your operating system, try to use `kubectl describe pod [podname]` and `kubectl logs [podname]` to see what happend.

**Comment by XuGuanghui6688** [comment]
Thank you very much for your patient answers. I checked the descriptions and logs of the relevant nodes, but I don’t know what caused the "ImagePullBackOff" or "ErrImagePull" problem. Is it because the relevant image is not pulled down?Does this require me to manually pull the mirror of the relevant service?
![Uploading imagepullback错误.png…]()

**Comment by kagaya85** [comment]
Because these service images are hosted on the Docker hub, try to pull image directly on your node server to make sure there is no problem with the network. 

use command like `docker pull codewisdom/ts-assurance-service:0.0.4` 

If can't pull the image directly from Docker hub, you may need do it manually.🤔

**Comment by XuGuanghui6688** [comment]
Thank you very much for your reply, which solved my problem. It may be the reason why my computer cannot bring 4 virtual machines. Sometimes the status of one of the 4 nodes in the cluster will become ‘NotReady’, which will cause the related services of Trainticket to fail to start. What I want to ask is when the status of these nodes must all be Running, can the Trainticket webpage be opened normally?

**Comment by kagaya85** [comment]
@XuGuanghui6688 Yeah of cause, if every thing goes well. But one more thing is that TrainTicket is too resource intensive, and since it has many services written in java, it may be a bit overwhelming for a single machine.🤯

**Comment by XuGuanghui6688** [comment]
Can I set up the system on different computers, then add the IP addresses of virtual machines created on different computers to the k8s cluster, and then run Trainticket on different computers. Is this feasible?

**Comment by kagaya85** [comment]
@XuGuanghui6688 Of course, and this is what we usually do.

**Comment by kagaya85** [comment]
It seems that no other problems need to be resolved, I will close this issue.

If you have other problems about using TrainTicket, feel free to open new issue.😀

**Comment by XuGuanghui6688** [comment]
Thank you very much for your answer, which resolved my current doubts.I tried to deploy the system on different machines.
