### ISSUE TITLE
Notification service need refactor

### ISSUE THREAD

**Issue by kagaya85** [FudanSELab/train-ticket#141]
### What would you like to be added

The way to send emails now makes no sense, we need to refactor `sendEmail` to a asynchronous method

### Why is this needed

See issue #113 and pr #136 , the notification service have some problem casued the sender service can't work correctly.

### Additional context

We can better decouple the notification service from other services by sending emails asynchronously via a message queue, because whether the email is sent successfully or not should not affect the booking service.

Or any other idea?

### Involved service
- [x] NotificationService
- [ ] CancelService
- [x] PreserveOtherService
- [x] PreserveService
- [x] Add a new **Message Queue**

**Comment by Humbertzhang** [comment]
We Add Message Queue between PreserveService and NotificationService,  PreserveOtherService and NotificationService, FoodService and Deleivery Service. 
Close this issue.
