### ISSUE TITLE
Ask for log and trace information

### ISSUE THREAD

**Issue by XuGuanghui6688** [FudanSELab/train-ticket#146]
Some time ago, I also tried to build the Trainticket system, but due to computer configuration and other reasons, it has not been successfully built yet.Therefore, I want to ask you for some logs and traces information of the TrainTicket microservice system. I want to see if we can do further experiments based on these logs and traces information. I guarantee that this information will only be used for academic research.

Thank you very much in advance.
My Email address is:Xuguanghui6688@163.com

**Comment by kagaya85** [comment]
Sorry, this is not in our responsibility, please setup your own experimental environment to collect logs and trace data.
