### ISSUE TITLE
Order service module artifact building error

### ISSUE THREAD

**Issue by Rakesh7295** [FudanSELab/train-ticket#154]
Error while building maven artifact
Command: mvn -Dpmd.failOnViolation=false -X clean  install

Module: 
1. ts-order-service
2. ts-order-other-service

ERROR::

1:48:04.826 [main] DEBUG org.springframework.test.web.servlet.setup.StandaloneMockMvcBuilder$StaticRequestMappingHandlerMapping - Looking up handler method for path /api/v1/orderservice/order/Sun May 09 11:48:04 IST 2021/train_number
11:48:04.827 [main] DEBUG org.springframework.test.web.servlet.setup.StandaloneMockMvcBuilder$StaticRequestMappingHandlerMapping - Returning handler method [public org.springframework.http.HttpEntity order.controller.OrderController.calculateSoldTicket(java.util.Date,java.lang.String,org.springframework.http.HttpHeaders)]
11:48:04.827 [main] DEBUG org.springframework.test.web.servlet.TestDispatcherServlet - Last-Modified value for [/api/v1/orderservice/order/Sun%20May%2009%2011:48:04%20IST%202021/train_number] is: -1
11:48:04.829 [main] DEBUG org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod - **Failed to resolve argument 0 of type 'java.util.Date'**
org.springframework.web.method.annotation.MethodArgumentTypeMismatchException: **Failed to convert value of type 'java.lang.String' to required type 'java.util.Date'; nested exception is** org.springframework.core.convert.ConversionFailedException: Failed to convert from type [java.lang.String] to type [@org.springframework.web.bind.annotation.PathVariable java.util.Date] for value 'Sun May 09 11:48:04 IST 2021'; nested exception is java.lang.IllegalArgumentException
..
..
..
..
..
..
..
11:48:04.868 [main] DEBUG org.springframework.test.web.servlet.TestDispatcherServlet - Successfully completed request
Tests run: 16, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 1.872 sec <<< FAILURE! - in order.controller.OrderControllerTest
testSecurityInfoCheck(order.controller.OrderControllerTest)  Time elapsed: 0.048 sec  <<< FAILURE!
java.lang.AssertionError: Status expected:<200> but was:<400>
	at org.springframework.test.util.AssertionErrors.fail(AssertionErrors.java:54)
	at org.springframework.test.util.AssertionErrors.assertEquals(AssertionErrors.java:81)
	at org.springframework.test.web.servlet.result.StatusResultMatchers$10.match(StatusResultMatchers.java:665)
	at org.springframework.test.web.servlet.MockMvc$1.andExpect(MockMvc.java:164)
	at order.controller.OrderControllerTest.testSecurityInfoCheck(OrderControllerTest.java:156)

testCalculateSoldTicket(order.controller.OrderControllerTest)  Time elapsed: 0.02 sec  <<< FAILURE!
java.lang.AssertionError: Status expected:<200> but was:<400>
	at org.springframework.test.util.AssertionErrors.fail(AssertionErrors.java:54)
	at org.springframework.test.util.AssertionErrors.assertEquals(AssertionErrors.java:81)
	at org.springframework.test.web.servlet.result.StatusResultMatchers$10.match(StatusResultMatchers.java:665)
	at org.springframework.test.web.servlet.MockMvc$1.andExpect(MockMvc.java:164)
	at order.controller.OrderControllerTest.testCalculateSoldTicket(OrderControllerTest.java:110)

Results :

Failed tests: 
  OrderControllerTest.testCalculateSoldTicket:110 Status expected:<200> but was:<400>
  OrderControllerTest.testSecurityInfoCheck:156 Status expected:<200> but was:<400>

**Comment by kagaya85** [comment]
Could you please provide some more parameters of the build environment, such as the JDK version, etc.

**Comment by Rakesh7295** [comment]
@kagaya85 Thanks for clarification
