### ISSUE TITLE
Failed pulling codewisdom/ts-delivery-service:latest

### ISSUE THREAD

**Issue by facefff** [FudanSELab/train-ticket#166]
# docker pull codewisdom/ts-delivery-service:latest
Error response from daemon: pull access denied for codewisdom/ts-delivery-service, repository does not exist or may require 'docker login'

**Comment by Humbertzhang** [comment]
@qsliu2017 will follow this issue and try to fix it. Thank you for your reporting.

**Comment by facefff** [comment]
> @qsliu2017 will follow this issue and try to fix it. Thank you for your reporting.

Thanks for reply. Besides, how could I reproduce the F1~F22 faults with k8s, download the fault branches and build them by myself?

**Comment by Humbertzhang** [comment]
> Thanks for reply. Besides, how could I reproduce the F1~F22 faults with k8s, download the fault branches and build them by myself?

Yes. We only maintain deploy files of master branch.

**Comment by qsliu2017** [comment]
@facefff Thanks for reporting. We update the deployment files. Please pull the latest version.

**Comment by Humbertzhang** [comment]
This issue has been fixed by https://github.com/FudanSELab/train-ticket/pull/167 , close.
