### ISSUE TITLE
请问一下程序的日志文件在哪个文件夹下

### ISSUE THREAD

**Issue by LangWeiXia** [FudanSELab/train-ticket#22]

**Comment by jichaofdu** [comment]
您好，
        有自动打日志，但没输出，都在控制台里，都是些docker执行日志，而且也没什么特别规范的日志，因为我们之前没使用到这部分，我们使用更多的主要是sleuth生成的trace日志。您可以用docker-compose部署docker-compose-zipkin分支，然后在 http://your-ip-address:9411/ 上看到收集到的trace日志。

**Comment by FengBotao119** [comment]
你好，请问如果用K8S部署的话，在哪里可以找到trace日志。
