### ISSUE TITLE
pods keep pending while follow qucick start to install

### ISSUE THREAD

**Issue by bigbanglwb** [FudanSELab/train-ticket#232]
### Summary
pods keep pending while follow qucick start 

### Current behaviour
I want to build train-ticket in my k8s cluster. I installed helm & openEBS, and run "make deploy". But it stop at 

mysql -h nacosdb-mysql-follower -u nacos -p
Waiting for mysql cluster of nacos to be ready ......
Waiting for 3 pods to be ready...

### Steps to reproduce 
I try to figure out the cause. I run "kubectl describe pods nacosdb-mysql-0",and the result is 

![image](https://user-images.githubusercontent.com/43382319/185897896-a992ed2f-5ce3-46e3-bef8-6efb4b72cb79.png)

It seems train-ticket  cannot bind PV correctly. I am sure that have installed openEBS.
![image](https://user-images.githubusercontent.com/43382319/185896964-b341bb23-8a0b-436b-81a0-baa02573d166.png)

### Your environment

OS(e.g: `cat /etc/os-release`):
ubuntu 20.04

docker version(e.g `docker version`): 
Client: Docker Engine - Community
 Version:           19.03.15
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        99e3ed8919
 Built:             Sat Jan 30 03:17:01 2021
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.15
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       99e3ed8919
  Built:            Sat Jan 30 03:15:30 2021
  OS/Arch:          linux/amd64
  Experimental:     false

**Comment by Deep-Yellow** [comment]
Before installing OpenEBS, try to run this command on the **Master** node: 
`kubectl taint nodes master node-role.kubernetes.io/master:NoSchedule-`
After installation is complete, set **openebs-hostpath** to the default StorageClass:
`kubectl patch storageclass openebs-hostpath -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'`

**Comment by behradmoeini** [comment]
Same problem!

**Comment by behradmoeini** [comment]
> 

When I try to run these commands, it says
`Error from server (NotFound): nodes "master" not found`

**Comment by Deep-Yellow** [comment]
> When I try to run these commands, it says
> `Error from server (NotFound): nodes "master" not found`

Replace it with the name of your master node.

**Comment by behradmoeini** [comment]
> > When I try to run these commands, it says
> > `Error from server (NotFound): nodes "master" not found`
> 
> Replace it with the name of your master node.

Thank you. I didn't set my master node name. I think it is the default. How can I determine my master node name?

**Comment by saibhargav97v** [comment]
Same problem!

**Comment by saibhargav97v** [comment]
@behradmoeini 
Run `hostname` and replace master with your hostname alias and run the above 2 commands. There's progress for me now. Thanks, @Deep-Yellow.

**Comment by behradmoeini** [comment]
> @behradmoeini Run `hostname` and replace master with your hostname alias and run the above 2 commands. There's progress for me now. Thanks, @Deep-Yellow.

Thank you for your reply. I used `hostname` and changed the command accordingly, but it gives me the error:
`Error from server (NotFound): nodes "Behrads-MacBook-Pro.local" not found`
which Behrads-MacBook-Pro.local is the hostname

**Comment by Deep-Yellow** [comment]
> 

try `kubectl get nodes` to get node name.

**Comment by mistycheney** [comment]
I'm getting this pod pending error again. The tainting steps do not solve it. Any ideas?

**My environment:**
Mac OS X 13.0

`docker verison`
Client:
 Cloud integration: v1.0.31
 Version:           20.10.23
 API version:       1.41
 Go version:        go1.18.10
 Git commit:        7155243
 Built:             Thu Jan 19 17:35:19 2023
 OS/Arch:           darwin/arm64
 Context:           desktop-linux
 Experimental:      true

Server: Docker Desktop 4.17.0 (99724)
 Engine:
  Version:          20.10.23
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.10
  Git commit:       6051f14
  Built:            Thu Jan 19 17:31:28 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.18
  GitCommit:        2456e983eb9e37e47538f59ea18f2043c9a73640
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

`kubectl version`
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-15T13:40:17Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:29:58Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/arm64"}
