### ISSUE TITLE
Nacos deployment unsuccessful because container initmysql always "Back-off restarting failed".

### ISSUE THREAD

**Issue by swimmingCreative** [FudanSELab/train-ticket#233]
### Summary
Tried to deploy train-ticket in with command failed:
make deploy DeployArgs="--all" Namespace=tt

### Expected behaviour

pod nacos-0 should be in "running" status.

### Current behaviour

pod nacos-0 is always in status "Init:0/1" -> "Init:Error" -> "Init:CrashLoopBackOff" -> "Init:0/1" ...
With command: "kubectl -n tt describe pods nacos-0", following information can be seen:
Events:
  Type     Reason     Age                              From                 Message
  ----     ------     ----                                     ----                 -------
  Normal   Scheduled  13m                   default-scheduler  Successfully assigned tt/nacos-0 to node1
  Normal   Pulled     11m (x5 over 13m)     kubelet            Container image "codewisdom/mysqlclient:0.1" already present on machine
  Normal   Created    11m (x5 over 13m)     kubelet            Created container initmysql
  Normal   Started    11m (x5 over 13m)     kubelet            Started container initmysql
  Warning  BackOff    3m31s (x47 over 13m)  kubelet            Back-off restarting failed container

With command: "kubectl -n tt logs nacos-0", following information can be seen:
"Error from server (BadRequest): container "k8snacos" in pod "nacos-0" is waiting to start: PodInitializing"

### Steps to reproduce 

cd ./train-ticket
make deploy DeployArgs="--all" Namespace=tt

### Your environment

OS(e.g: `cat /etc/os-release`):
centos -7.6

docker version(e.g `docker version`): 
Docker version 20.10.17, build 100c701

 
docker-compose version (e.g `docker-compose --version`):
docker-compose version 1.18.0, build 8dd22a9

 
Kubernetes version(use `kubectl version`):
v1.22.0

istio version: 
v1.14.2

**Comment by swimmingCreative** [comment]
The root cause is all of the nacosdb is follower, and the mysql 'read-only' is 1. After the root cause is solved, this problem is solved.

**Comment by saibhargav97v** [comment]
Hi @swimmingCreative, I was able to set 1 leader and 2 followers but the issue remains the same. How to set mysql 'read-only' ?
