### ISSUE TITLE
What's the version of k8s?

### ISSUE THREAD

**Issue by swimmingCreative** [FudanSELab/train-ticket#235]
### Summary
When I tried to deploy the kibana and filebeat, I noticed that the elasticsearch is 7.1.0。When I deploy the kibana 7.1.0 and filebeat 7.1.0 with elastic/helm-chart，both of them are failed. Then, I tried efk 7.6.0, efk7.13.0. Both of them are failed.

My k8s is v1.22.0, can author share what's the version of your k8s?

### Your environment

OS(e.g: `cat /etc/os-release`):

docker version(e.g `docker version`): 

 
docker-compose version (e.g `docker-compose --version`):

 
Kubernetes version(use `kubectl version`):

istio version:

**Comment by Deep-Yellow** [comment]
We've tried it before, and v1.22.0 works.
