### ISSUE TITLE
docker服务访问

### ISSUE THREAD

**Issue by jjcaowei** [FudanSELab/train-ticket#24]
请问我在本地虚拟机中启动了所有的服务，我在外部的宿主主机里如何访问docker服务？

**Comment by liuZOZO** [comment]
你好：
   1. 如果你是用docker-compose 部署的， 只需要在本地浏览器输入部署机器的ip 就可以了（你可以看一下ts-ui-service的端口, 这个是网页文件，使用的是nginx，默认端口80）,
   2.  如果你用k8s， istio 了，应该是master 的 ip: 31380  就可以访问到了。




308762585@qq.com
 
发件人： jjcaowei
发送时间： 2019-03-14 14:51
收件人： FudanSELab/train-ticket
抄送： Subscribed
主题： [FudanSELab/train-ticket] docker服务访问 (#24)
请问我在本地虚拟机中启动了所有的服务，我在外部的宿主主机里如何访问docker服务？

**Comment by jjcaowei** [comment]
你好：
    我试了你给的方案，但是我的问题并没有解决（我是在windows10系统上创建的一个linux虚拟机，然后用docker-compose部署服务的，然后在windows上打开浏览器访问）。请问我需要在windows上配置什么东西嘛，有什么合适的解决方案吗？

**Comment by liuZOZO** [comment]
哦， 原来你用的是本地虚拟机。
           你这应该是虚拟机和本地网络之间设置的问题，你看一下这个博客：https://blog.csdn.net/qq_21119513/article/details/80436947。
如果这个还不行，你可以单独试试docker 部署一个新的nginx, 看看本地浏览器能不能访问到nginx 的index 页面。




308762585@qq.com
 
发件人： jjcaowei
发送时间： 2019-03-15 17:42
收件人： FudanSELab/train-ticket
抄送： liuZOZO; Comment
主题： Re: [FudanSELab/train-ticket] docker服务访问 (#24)
你好：
我试了你给的方案，但是我的问题并没有解决（我是在windows10系统上创建的一个linux虚拟机，然后用docker-compose部署服务的，然后在windows上打开浏览器访问）。请问我需要在windows上配置什么东西嘛，有什么合适的解决方案吗？
