### ISSUE TITLE
你好！请问有完整的版本列表吗？尝试了多个版本组合都部署失败

### ISSUE THREAD

**Issue by Buenbk** [FudanSELab/train-ticket#249]
目前的前置工具包括：docker, k8s, helm, openebs -- ubuntu18.04
这四个工具我首先尝试了全部最新版本——失败，k8s跟docker不兼容
第二次，我尝试了k8s=1.23.1-00， docker=20.10.6， Helm=3.9.4， openebs最新（官方提供的helm仓库以及其他的helm仓库都无法提供2.12版本，只有最新版和1.1.1版），依旧部署失败

部署采用的是make deploy，失败是发现kubelet正常运行但是有很多报错，网上找不到解决方案，**因此怀疑是版本组合问题。**

**### 希望可以提供各类工具的部署版本，谢谢！**

**Comment by Deep-Yellow** [comment]
你好，可以参考这个文档：https://ttdoc.oss-cn-hongkong.aliyuncs.com/Steps.pdf

**Comment by keidododo** [comment]
> 

您好，请问您部署成功了嘛？openebs您装的是2.12.x嘛？
