### ISSUE TITLE
请问对机器资源的要求

### ISSUE THREAD

**Issue by LPN1997** [FudanSELab/train-ticket#25]
请问k8s+istio的部署方案需要多少机器资源？CPU，MEM和DISK需要多少才能稳定运行？

**Comment by liuZOZO** [comment]
您好！

   我们自己平时用的是学校的虚拟机，配置都是一样的（ 23G 内存， 50G 磁盘， 有8个CPU(1 core， 3.00GHZ) )
   
   单独docker-compose 一台就够了， k8s( +isito)  最少3台！

谢谢！ 

祝好！


复旦大学软件工程
上海市浦东新区蔡伦路1159号，复旦大学，201203 
No.1159, Cailun Road, Zhangjiang Hi-Tech Park, Pudong New District, Shanghai, 201203
 
发件人： LPN1997
发送时间： 2019-05-22 18:40
收件人： FudanSELab/train-ticket
抄送： Subscribed
主题： [FudanSELab/train-ticket] 请问对机器资源的要求 (#25)
请问k8s+istio的部署方案需要多少机器资源？CPU，MEM和DISK需要多少才能稳定运行？

**Comment by LPN1997** [comment]
非常感谢，另外3台这种配置的虚拟机是测试后得出的结论吗？请问这种配置下对CPU和MEM的占用会达到多少呢？
我自己在3 * 8G，3 * 8 core(1GHz)的虚拟机尝试部署过k8s的版本，对硬件资源的消耗不是很高，但如果再加上istio就会马上出现CPU和内存使用都达到100%然后卡死的情况。

**Comment by liuZOZO** [comment]
这个没测试过，一般机器配置越差，启动时间会越长，我们的这个3台机器，其实我们都觉得启动比较慢，一般为了启动速度快一点，都使用4台这种配置的虚拟机，服务完全启动好也差不多需要5分钟。

**Comment by LPN1997** [comment]
好的，多谢！

**Comment by bdqfork** [comment]
@liuZOZO 你好，我想请问下，k8s集群的服务器配置详细如何，是3台8核cpu，8g内存的吗？我部署的时候资源不够用了，想请问一下

**Comment by liuZOZO** [comment]
请查看常见问题：
https://github.com/FudanSELab/train-ticket/wiki/FAQ

8G 内存没试过，不过4台24G 内存的，部署完k8s, isito 加trainticket 服务，master 的内存都不多了
