### ISSUE TITLE
deployment failed

### ISSUE THREAD

**Issue by WaldenLeefx** [FudanSELab/train-ticket#253]
### Summary
the second step of deployment failed:'Error: INSTALLATION FAILED: cannot re-use a name that is still in use' and 'Error from server (NotFound): statefulsets.apps "tsdb-mysql" not found'.

the third step of deployment has error info list as follow, I want know whether it will affect the deployment.

### Current behaviour

[root@vm-node-71 train-ticket]# make deploy DeployArgs="--with-tracing --with-monitoring"
args num: 2
Parse DeployArgs
--with-tracing
--with-monitoring
Start deployment Step <1/3>------------------------------------
Start to deploy mysql cluster for nacos.
NAME: nacosdb
LAST DEPLOYED: Sat Jan 28 21:46:14 2023
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
The cluster is comprised of 3 pods: 1 leader and 2 followers. Each instance is accessible within the cluster through:

    <pod-name>.nacosdb-mysql

To connect to your database:

1. Get mysql user `nacos`'s password:

    kubectl get secret -n default nacosdb-mysql -o jsonpath="{.data.mysql-password}" | base64 --decode; echo

2. Run an Ubuntu pod that you can use as a client:

    kubectl run ubuntu -n default --image=ubuntu:focal -it --rm --restart='Never' -- bash -il

3. Install the mysql client:

    apt-get update && apt-get install mysql-client -y

4. To connect to leader service in the Ubuntu pod:

    mysql -h nacosdb-mysql-leader -u nacos -p

5. To connect to follower service (read-only) in the Ubuntu pod:

    mysql -h nacosdb-mysql-follower -u nacos -p
Waiting for mysql cluster of nacos to be ready ......
Waiting for 3 pods to be ready...
Waiting for 2 pods to be ready...
Waiting for 1 pods to be ready...
partitioned roll out complete: 3 new pods have been updated...
Start to deploy nacos.
NAME: nacos
LAST DEPLOYED: Sat Jan 28 21:47:10 2023
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
Waiting for nacos to be ready ......
Waiting for 3 pods to be ready...
Waiting for 2 pods to be ready...
Waiting for 1 pods to be ready...
partitioned roll out complete: 3 new pods have been updated...
Start to deploy rabbitmq.
NAME: rabbitmq
LAST DEPLOYED: Sat Jan 28 21:47:17 2023
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
Waiting for rabbitmq to be ready ......
Waiting for deployment "rabbitmq" rollout to finish: 0 of 1 updated replicas are available...
deployment "rabbitmq" successfully rolled out
End deployment Step <1/3>--------------------------------------
Start deployment Step <2/3>: mysql cluster of train-ticket services----------------------
Error: INSTALLATION FAILED: cannot re-use a name that is still in use
Waiting for mysql cluster of train-ticket to be ready ......
Error from server (NotFound): statefulsets.apps "tsdb-mysql" not found
End deployment Step <2/3>-----------------------------------------------------------------
Start deployment Step <3/3>: train-ticket services--------------------------------------------
Start to deploy secret of train-ticket services.
Start to deploy train-ticket deployments with skywalking agent.
sed：无法读取 s/nacos/nacos/g：没有那个文件或目录
sed：无法读取 s/rabbitmq/rabbitmq/g：没有那个文件或目录
End deployment Step <3/3>----------------------------------------------------------------------
Start deploy skywalking
service/elasticsearch created
deployment.apps/elasticsearch created
configmap/skywalking-cm created
deployment.apps/skywalking created
service/skywalking created
deployment.apps/skywalking-ui created
service/skywalking-ui created
Start deploy prometheus and grafana
configmap/alertmanager-config unchanged
deployment.apps/alertmanager unchanged
service/alertmanager unchanged
deployment.apps/alertsnitch-mysql unchanged
service/alertsnitch-mysql unchanged
deployment.apps/alertsnitch unchanged
service/alertsnitch unchanged
deployment.apps/grafana-core unchanged
service/grafana unchanged
service/node-exporter unchanged
daemonset.apps/node-exporter unchanged
configmap/prometheus-config unchanged
configmap/prometheus-rules unchanged
clusterrolebinding.rbac.authorization.k8s.io/kube-state-metrics unchanged
clusterrole.rbac.authorization.k8s.io/kube-state-metrics unchanged
deployment.apps/kube-state-metrics unchanged
serviceaccount/kube-state-metrics unchanged
service/kube-state-metrics unchanged
serviceaccount/prometheus unchanged
clusterrole.rbac.authorization.k8s.io/prometheus unchanged
clusterrolebinding.rbac.authorization.k8s.io/prometheus unchanged
deployment.apps/prometheus unchanged
service/prometheus unchanged
[root@vm-node-71 train-ticket]#

### Your environment

OS(e.g: `cat /etc/os-release`):

docker version(e.g `docker version`): 

 
docker-compose version (e.g `docker-compose --version`):

 
Kubernetes version(use `kubectl version`):

istio version:

**Comment by Hawward** [comment]
How did you fix this issue?

**Comment by faridahmadpour** [comment]
@WaldenLeefx 
Hi,
I have the same issue. Would you explain how you resolved it and what the problem was?
