### ISSUE TITLE
ts-consign-price-service pod  CrashLoopBackOff

### ISSUE THREAD

**Issue by WaldenLeefx** [FudanSELab/train-ticket#254]
### Summary
ts-consign-price-service pod  CrashLoopBackOff
Events:
  Type     Reason     Age                    From     Message
  ----     ------     ----                   ----     -------
  Warning  Unhealthy  9m21s (x153 over 93m)  kubelet  Readiness probe failed: dial tcp 192.168.63.191:16110: connect: connection refused
  Warning  BackOff    4m21s (x243 over 89m)  kubelet  Back-off restarting failed container
### Expected behaviour

ts-consign-price-service pod Running

### Current behaviour

kubectl describe pods ts-consign-price-service-5546df8657-j4jzd
Name:             ts-consign-price-service-5546df8657-j4jzd
Namespace:        default
Priority:         0
Service Account:  default
Node:             vm-node-71/10.60.150.71
Start Time:       Tue, 31 Jan 2023 12:19:06 +0800
Labels:           app=ts-consign-price-service
                  pod-template-hash=5546df8657
Annotations:      cni.projectcalico.org/containerID: 8e446ea53a9469c3d08d5fd611e150f6197538a84df8f21c056120273b566de9
                  cni.projectcalico.org/podIP: 192.168.63.191/32
                  cni.projectcalico.org/podIPs: 192.168.63.191/32
                  kubectl.kubernetes.io/restartedAt: 2023-01-31T04:19:06Z
Status:           Running
IP:               192.168.63.191
IPs:
  IP:           192.168.63.191
Controlled By:  ReplicaSet/ts-consign-price-service-5546df8657
Init Containers:
  agent-container:
    Container ID:  docker://1fd87f0a4778389a4765ac0964f63504b85e9f4de6bbd46022ef56e35dadb79f
    Image:         apache/skywalking-java-agent:8.8.0-alpine
    Image ID:      docker-pullable://apache/skywalking-java-agent@sha256:bf1855ed4eb9f7042c1c25c7147e7abda329851c7dcb0c1960dbe94485a45202
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
    Args:
      -c
      cp -R /skywalking/agent /agent/
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Tue, 31 Jan 2023 12:19:07 +0800
      Finished:     Tue, 31 Jan 2023 12:19:07 +0800
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /agent from skywalking-agent (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-vf8j4 (ro)
Containers:
  ts-consign-price-service:
    Container ID:   docker://899147ff3868d9d58cd1ad6d1fa9a1e14d8eba5b7a0150dacbb2ed9f48a80a9a
    Image:          codewisdom/ts-consign-price-service:1.0.0
    Image ID:       docker-pullable://codewisdom/ts-consign-price-service@sha256:6c358edcb840bff38940a0f6cd76279341f7861eac5f9a39c3ab9f023f59608a
    Port:           16110/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Tue, 31 Jan 2023 13:49:52 +0800
      Finished:     Tue, 31 Jan 2023 13:52:24 +0800
    Ready:          False
    Restart Count:  15
    Limits:
      cpu:     500m
      memory:  2000Mi
    Requests:
      cpu:      100m
      memory:   300Mi
    Readiness:  tcp-socket :16110 delay=60s timeout=5s period=10s #success=1 #failure=3
    Environment Variables from:
      ts-consign-price-mysql  Secret     Optional: false
      nacos                   ConfigMap  Optional: false
    Environment:
      NODE_IP:                               (v1:status.hostIP)
      SW_AGENT_COLLECTOR_BACKEND_SERVICES:  skywalking:11800
      SW_GRPC_LOG_SERVER_HOST:              skywalking
      SW_GRPC_LOG_SERVER_PORT:              11800
      SW_AGENT_NAME:                         (v1:metadata.labels['app'])
      JAVA_TOOL_OPTIONS:                    -javaagent:/skywalking/agent/skywalking-agent.jar
    Mounts:
      /skywalking from skywalking-agent (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-vf8j4 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  skywalking-agent:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  kube-api-access-vf8j4:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                    From     Message
  ----     ------     ----                   ----     -------
  Warning  Unhealthy  9m21s (x153 over 93m)  kubelet  Readiness probe failed: dial tcp 192.168.63.191:16110: connect: connection refused
  Warning  BackOff    4m21s (x243 over 89m)  kubelet  Back-off restarting failed container

### Your environment

OS(e.g: `cat /etc/os-release`):
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
docker version(e.g `docker version`): 
Client: Docker Engine - Community
 Version:           20.10.22
 API version:       1.41
 Go version:        go1.18.9
 Git commit:        3a2c30b
 Built:             Thu Dec 15 22:30:24 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.22
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.9
  Git commit:       42c8b31
  Built:            Thu Dec 15 22:28:33 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.15
  GitCommit:        5b842e528e99d4d4c1686467debf2bd4b88ecd86
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
 
docker-compose version (e.g `docker-compose --version`):

 
Kubernetes version(use `kubectl version`):
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-08T19:58:30Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.15", GitCommit:"b84cb8ab29366daa1bba65bc67f54de2f6c34848", GitTreeState:"clean", BuildDate:"2022-12-08T10:42:57Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.26) and server (1.23) exceeds the supported minor version skew of +/-1

istio version:

**Comment by Deep-Yellow** [comment]
When container is started, it will initialize data, and repeated data insertion causes errors.

We are aware of this bug and are planning to fix it. In current, you can solve this by cleaning up the persistent data and setting this service as single instance.

**Comment by Buenbk** [comment]
> When container is started, it will initialize data, and repeated data insertion causes errors.
> 
> We are aware of this bug and are planning to fix it. In current, you can solve this by cleaning up the persistent data and setting this service as single instance.
 How to clean up the persistent data and set service as single instance?

**Comment by Buenbk** [comment]
> When container is started, it will initialize data, and repeated data insertion causes errors.
> 
> We are aware of this bug and are planning to fix it. In current, you can solve this by cleaning up the persistent data and setting this service as single instance.

How to clean up the persistent data and set service as single instance?

**Comment by Buenbk** [comment]
hello！I encountered the same problem.  Have you solve it? Could you please share your solutions?
