### ISSUE TITLE
pod 'ts-consign-price-service' and 'alertmanager' CrashLoopBackOff

### ISSUE THREAD

**Issue by Buenbk** [FudanSELab/train-ticket#257]
Could you please tell me how to clean up the persistent data and set 'ts-consign-price-service' as single instance?

error info of alertmanager:
`msg="Loading configuration file failed" file=/etc/config/alertmanager.yml err="no global SMTP smarthost set"`
By the way, is alertmanager neccesary? I just want to collet some data(logs, traces, metrics)

**Comment by Deep-Yellow** [comment]
To clean up the persistent data
1. make reset-deploy
2. some database pods may need `help list` to view, and destroy them with `helm uninstall`
3. clean pvc and pv

alertmanager is used to configure alerting rules. If you don't need it, just ignore it
