### ISSUE TITLE
部署完成后无法访问ElasticSearch，系统没有启动9200端口

### ISSUE THREAD

**Issue by Buenbk** [FudanSELab/train-ticket#258]
pod正常运行：
![image](https://user-images.githubusercontent.com/82649417/218385613-747ebcbf-6fe4-4e53-b30a-e43a0b7f94b5.png)
浏览器无法访问9200端口：
![image](https://user-images.githubusercontent.com/82649417/218385681-6154d161-c2c4-46e7-8789-8c4c0c2a8dea.png)
系统中也找不到该端口：
![image](https://user-images.githubusercontent.com/82649417/218385755-417e0210-e2d8-4ab1-aa4c-caaacb7b04e1.png)

**Comment by Buenbk** [comment]
其他一些组件工具包括prometheus（9090）也无法访问
只有TrainTicket微服务本身可以正常访问

**Comment by JasonBourne1998** [comment]
> 其他一些组件工具包括prometheus（9090）也无法访问 只有TrainTicket微服务本身可以正常访问

Hi @Buenbk , 请问你解决elasticsearch的问题了吗？
