### ISSUE TITLE
trainticket-gateway配置错误

### ISSUE THREAD

**Issue by LPN1997** [FudanSELab/train-ticket#26]
deployment/k8s-deployment-v0.0.2/trainticket-gateway.yaml中一些service的uri prefix与ts-ui-dashboard中配置的不符。
比如dashboard里travel service的uri prefix是/travel，而gateway中配置的却是/api/v1/travelservice。

我猜你们是想统一后端服务的接口，但ts-ui-dashboard的配置还没改过来？

**Comment by liuZOZO** [comment]
ts-ui-dashboard 的nginx.conf 里面那些没有/api/v1的是过时的，还没有完全删除



308762585@qq.com
 
发件人： LPN1997
发送时间： 2019-05-23 12:18
收件人： FudanSELab/train-ticket
抄送： Subscribed
主题： [FudanSELab/train-ticket] trainticket-gateway配置错误 (#26)
deployment/k8s-deployment-v0.0.2/trainticket-gateway.yaml中一些service的uri prefix与ts-ui-dashboard中配置的不符。
比如dashboard里travel service的uri prefix是/travel，而gateway中配置的却是/api/v1/travelservice。
我猜你们是想统一后端服务的接口，但ts-ui-dashboard的配置还没改过来？
