### ISSUE TITLE
skywalking只有trace数据没有log数据

### ISSUE THREAD

**Issue by Buenbk** [FudanSELab/train-ticket#260]
有调用链数据：
![image](https://user-images.githubusercontent.com/82649417/218469559-1a2db9ea-be82-45d5-85b8-5d233d3485d2.png)

但是没有日志数据：
![image](https://user-images.githubusercontent.com/82649417/218469669-b380dde2-dd02-4716-9f9c-f17f30506880.png)

**请问默认没有给skywalking配置日志收集功能吗？我部署是采用了make deploy DeployArgs="--with-tracing --with-monitoring"。如果要收集日志的话要怎么操作呢？**

**Comment by Buenbk** [comment]
请问是程序中没有集成日志框架吗，但是我看DeepTraLog论文中说skywalking收集日志并存到elasticsearch中

**Comment by Buenbk** [comment]
elastichsearch的日志数据似乎也是空的，没有日志数据

**Comment by Buenbk** [comment]
请问我需要自己手动给所有service添加logback这种日志框架依赖来支持skywalking的日志收集吗？

**Comment by Deep-Yellow** [comment]
skywalking是可以收集日志的，但是需要自己进行配置，可以查看一下skywalking的文档。

**Comment by Deep-Yellow** [comment]
> 请问我需要自己手动给所有service添加logback这种日志框架依赖来支持skywalking的日志收集吗？

不需要自己手动给所有service添加logback这种日志框架，也不需要修改代码和部署文件

**Comment by Buenbk** [comment]
> > 请问我需要自己手动给所有service添加logback这种日志框架依赖来支持skywalking的日志收集吗？
> 
> 不需要自己手动给所有service添加logback这种日志框架，也不需要修改代码和部署文件

无论是官方文档还是技术论坛，用skywalking收集日志的每个方法都需要添加log4j,logback这种日志框架

**Comment by YanXiaoBai** [comment]
> > > 请问我需要自己手动给所有service添加logback这种日志框架依赖来支持skywalking的日志收集吗？
> > 
> > 
> > 不需要自己手动给所有service添加logback这种日志框架，也不需要修改代码和部署文件
> 
> 无论是官方文档还是技术论坛，用skywalking收集日志的每个方法都需要添加log4j,logback这种日志框架

我一开始也遇到了这个问题，研究了几天后得到了部署方法。
首先SkyWalking进行Log收集的JavaAgent和Logback都已经在官方给出的Docker镜像中配置完成了，因此需要实际配置的只有logback.xml，而由于make deploy DeployArgs="--with-tracing"并不会将本地的微服务进行编译，而是会将已经打包好的docker镜像直接部署到K8s服务器上，因此在服务的/src/main/resources/文件夹中直接添加ogback.xml是没有用的。
为了避免重新使用docker对项目进行编译打包，我使用了K8s的ConfigMap机制来在创建pod容器时向容器内添加配置文件，并设置java运行选项来让SpringBoot加载配置文件，具体来说只需要对工程的/deployment/kubernetes-manifests/quickstart-k8s/yamls/sw_deploy.yaml.sample文件进行修改，替换成如下文件即可。
[https://github.com/YanXiaoBai/train-ticket-yaml/blob/main/sw_deploy.yml](https://github.com/YanXiaoBai/train-ticket-yaml/blob/main/sw_deploy.yml)
将原工程下的该文件进行替换后，执行make deploy DeployArgs="--with-tracing"就可以实现SkyWalking的日志收集。
