### ISSUE TITLE
choice of food in preserve-svc call food-svc

### ISSUE THREAD

**Issue by WaldenLeefx** [FudanSELab/train-ticket#264]
### Summary
在使用UI界面预定火车票时，未选择食物备选框，在skywalking中仍监控到food-svc的调用

### Expected behaviour

未选择食物备选框时，在skywalking中应监控到无food-svc的调用。推测是UI界面备选框代码出现问题？

**Comment by Deep-Yellow** [comment]
已记录这个bug，十分感谢
