### ISSUE TITLE
关于zipkin的小问题

### ISSUE THREAD

**Issue by LPN1997** [FudanSELab/train-ticket#27]
我注意到这个项目里似乎有许多使用zipkin的痕迹[捂脸]，请问这个项目是支持k8s+istio环境下使用zipkin收集trace数据的吗？如果支持，可以告知操作方法吗？（我自己使用istio自带的zipkin似乎并不起作用，是还要修改什么配置吗？）

**Comment by liuZOZO** [comment]
把你微信给我，我来加你

**Comment by LPN1997** [comment]
已发qq邮箱

**Comment by LPN1997** [comment]
你好，请问收到邮件了吗？我发的是308762585@qq.com，是邮箱有误吗？

**Comment by liuZOZO** [comment]
我收到了，不过你发的微信号怎末收不到，我回信你的163邮箱了

**Comment by bdqfork** [comment]
@liuZOZO 你好，我也有这个问题，能给解释一下吗？

**Comment by liuZOZO** [comment]
使用istio 中的zipkin 是可以收集到trace 的（你应该注意到了istio  中没有部署zipkin 的pod, 需要你自己部署）
