### ISSUE TITLE
你好，为什么购买的票的价格和订单里显示的价格不一样？

### ISSUE THREAD

**Issue by lhzxxy** [FudanSELab/train-ticket#28]
购买的是一等座的票：
![image](https://user-images.githubusercontent.com/39483165/58369656-de395300-7f2f-11e9-8b72-8879485711ff.png)
订单列表显示的是二等座的价格：
![image](https://user-images.githubusercontent.com/39483165/58369672-1771c300-7f30-11e9-9db7-e38595e8c19d.png)
购买的是二等座的票：
![image](https://user-images.githubusercontent.com/39483165/58369684-530c8d00-7f30-11e9-811c-a50a36c101fe.png)
订单列表显示的是一等座的价格：
![image](https://user-images.githubusercontent.com/39483165/58369695-80f1d180-7f30-11e9-90a6-937a79d94e77.png)

**Comment by lhzxxy** [comment]
好像是因为client_ticket_book.js里面：

                    if($("#sub_setType").text().indexOf("confort")) {
                        orderTicketInfo.seatType = "2";
                    }else {
                        orderTicketInfo.seatType = "3";
                    }
如果座位类型是confort seat，条件是0，为false，所以执行orderTicketInfo.seatType = "3";
如果座位类型是economy seat，条件是-1，为true，所以执行orderTicketInfo.seatType = "2";

**Comment by liuZOZO** [comment]
你好! 是的，谢谢指出，我刚定位到这里你就发来了【赞】 ，马上我更新一下

**Comment by liuZOZO** [comment]
请问你用的是docker-compose 还是k8s？

**Comment by liuZOZO** [comment]
我看了那块不能那样写，不能简单区分2，3 对于k字头和z 字头是有问题的，我们最近在重构，谢谢指出！

**Comment by lhzxxy** [comment]
> 请问你用的是docker-compose 还是k8s？

我用的是docker-compose。
然后好像这里也有点问题，导致confirm ticket显示的价格只能是22.5或50：
     if (seatType == "2" || seatType == 2) {
         seatPrice = "50";
         seatType = "confort seat";
     } else {
         seatPrice = "22.5";
         seatType = "economy seat";
     }

**Comment by liuZOZO** [comment]
是的，我看到了，其中在购买Z 字头的时侯，还有一个post 请求方式的错误，这是我们后台重构后前台没完全测试完成

**Comment by liuZOZO** [comment]
你要方便的话，可以用k8s部署在测试测试
