### ISSUE TITLE
关于搜索停靠车站数最少的车次的问题

### ISSUE THREAD

**Issue by lhzxxy** [FudanSELab/train-ticket#29]
你好：
RoutePlanServiceImpl.java的searchMinStopStations方法的：

        for(int i = 0; i < Math.min(info.getNum(),routeList.size()); i++){
            int minIndex = 0;
            int tempMinGap = Integer.MAX_VALUE;
            for(int j = 0; j < gapList.size(); j++){
                if(gapList.get(j) < tempMinGap){
                    tempMinGap = gapList.get(j);
                    minIndex = j;
                }
            }
            resultRoutes.add(routeList.get(minIndex).getId());
            routeList.remove(minIndex);
        }
routeList.remove(minIndex);这一行是不是有点问题，例如：从南京到上海有4条路线，一开始的时候i是0，info.getNum()固定是5，routeList.size()是4，第一次循环以后，i是1，routeList.size()是3，第二次循环以后，i是2，routeList.size()是2，退出循环，只查到2条路线。搜索结果如图：
![image](https://user-images.githubusercontent.com/39483165/58411048-0054e180-80a6-11e9-8e75-6408f762be3a.png)

**Comment by liuZOZO** [comment]
谢谢指出！确实是bug, 最多只返回5条
