### ISSUE TITLE
开源故障数据集

### ISSUE THREAD

**Issue by jjcaowei** [FudanSELab/train-ticket#31]
请问你们团队会考虑开源一些关于微服务故障中的数据集吗？

**Comment by liuZOZO** [comment]
这个目前可以从论文的 Replication Package 数据集里面得到，我们会考虑开源数据集的，本来还打算租外网服务器把我们的系统部署上去，让大家访问，产生的数据公开的，不过费用还是不小的

**Comment by jjcaowei** [comment]
嗯嗯


| |
18516611755
邮箱：18516611755@163.com
|

Signature is customized by Netease Mail Master

在2019年07月02日 22:39，liuZOZO 写道：

Closed #31.
