### ISSUE TITLE
Lost connection to MySQL Server during query

### ISSUE THREAD

**Issue by wdongyu** [FudanSELab/train-ticket#32]
**Describe the bug**
When running Train-Ticket system on K8S with istio, **ts-voucher-service** attempt a connection to **ts-voucher-mysql**, but the connection fails and the **ts-voucher-service** pod keeps restarting. Following is the error log of the **ts-voucher-service** pod.

![image](https://user-images.githubusercontent.com/23725216/60517081-a03f0400-9d11-11e9-83fa-2f2005b00384.png)

**Expected behavior**
The connection should succeed and all pods are running.

**Steps to reproduce the bug**
Follow the install instructions in Wiki:
1. Build docker image
1. Upload docker image to my own registry
1. Deploy the system on K8S with istio in an auto-injection namespace

Then the pod crash.

**Version**
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-30T21:39:16Z", GoVersion:"go1.11.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:36:14Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

```
$ istioctl version
client version: 1.2.0
citadel version: 1.2.0
galley version: 1.2.0
ingressgateway version: 1.2.0
pilot version: 1.2.0
policy version: 1.2.0
sidecar-injector version: 1.2.0
telemetry version: 1.2.0
```

**Installation**
Customizable Install with Helm

**Comment by liuZOZO** [comment]
Maybe this will be help. but not everybody will encounter this probolem.

https://github.com/istio/istio/issues/10062
