### ISSUE TITLE
client_order_list.html刷新时数据有时会重复

### ISSUE THREAD

**Issue by lhzxxy** [FudanSELab/train-ticket#33]
刷新client_order_list.html时，数据有时会重复出现：
![image](https://user-images.githubusercontent.com/39483165/60769033-d6a7c500-a0fd-11e9-8827-f08702055197.png)
有时又不会：
![image](https://user-images.githubusercontent.com/39483165/60769046-f9d27480-a0fd-11e9-874c-c3df840fe49c.png)

**Comment by liuZOZO** [comment]
你好，请问你用的是最新发布的代码吗？我这边怎么刷新都是没有重复的啊

**Comment by lhzxxy** [comment]
> 你好，请问你用的是最新发布的代码吗？我这边怎么刷新都是没有重复的啊

我用的是0.0.1的，试了Chrome和火狐都有时会这样，很奇怪。。。

**Comment by lhzxxy** [comment]
> 你好，请问你用的是最新发布的代码吗？我这边怎么刷新都是没有重复的啊
![ooxyq-docz8](https://user-images.githubusercontent.com/39483165/60769188-45d1e900-a0ff-11e9-82d4-95d2de1ea0cb.gif)

**Comment by liuZOZO** [comment]
对的， V 0.0.1 界面存在不少问题， 你仔细看看选择的金额，添加联系人，其实都有bug

**Comment by lhzxxy** [comment]
> 对的， V 0.0.1 界面存在不少问题， 你仔细看看选择的金额，添加联系人，其实都有bug

好的~很奇怪，没看出来是为什么。。

**Comment by liuZOZO** [comment]
在V0.0.2 里面已经修复了，有问题的话，可以把你微信发我加你微信

**Comment by liuZOZO** [comment]
js  异步
