### ISSUE TITLE
异常注入

### ISSUE THREAD

**Issue by iwtbs** [FudanSELab/train-ticket#34]
您好，我们现在希望在trainticket系统中注入异常，在调用链中做根因定位。看到了您这边有一个fault的项目，每个异常都有单独的docker compose，而且每个异常的容器和trainticket的容器改动比较大（比如F1异常在ts-auth-service;ts-click-twice;ts-common;ts-launcher;ts-login;ts-payment,tsp-core,tsp-dashboard;ts-register;ts-sso;ts-ui-test;ts-user-service这十二个容器有差异）。我们现在希望并不是重新搭建一个新的系统，而是在原先的系统中做一些更改（比如通过istio重定向到异常容器，正常容器不变），即要在目前版本上复现应该改哪些地方?

**Comment by liuZOZO** [comment]
您好！ 下面这些分支是对应的有fault 的分支，但是这些是基于旧版本的， 不是当前master 分支。
所以你上面提到的ts-auth 描述F1 是不对的。   

下面这些是有故障的分支.  
 异常的容器可以基于下面的打包，
正常的容器就不能使用master 的分支了， 可以看一下使用不带error 或 fault 的 分支就应该是对应的正常的代码。

建议: 
1.  先理解每个故障的意思
2.  自己基于老的分支代码 或 master 分支的代码，自己复现


F1 ts-error-process-seq

F2 ts-error-reportui

F3 ts-error-docker-JVM

F4 ts-error-ssl

F5 ts-error-cross-timeout-status(chance)

F7 ts-external-normal

F8 ts-error-redis

F10 ts-error-normal

F11 ts-error-bomupdate

F12 ts-error-processes-seq-status(chance)

F13 ts-error-queue
