### ISSUE TITLE
调用链分析

### ISSUE THREAD

**Issue by iwtbs** [FudanSELab/train-ticket#41]
您好，我搭建了这个trainticket项目，并且收集了调用链的数据，发现存在非常多的服务存在自调用的情况，请问从程序设计角度来看这种原因是什么呢？

**Comment by jichaofdu** [comment]
您好，我们也注意到了这个问题。在开发每个服务的时候我们只是规定了这个服务需要实现哪些功能，而并没有说明这些功能会被哪些其他服务使用，以及使用的方法。功能的开发者在编写代码的过程中为了实现功能而调用了现有的已经完成的其他服务的功能的API，就容易出现这种互相依赖的情况。
我们之前写这个的时候也没有组织的很好所以造成了一些混乱，非常抱歉
