### ISSUE TITLE
fault inject

### ISSUE THREAD

**Issue by iwtbs** [FudanSELab/train-ticket#43]
您好，我是清华裴丹老师的同学，我们现在的一些实验数据是基于tratinticket系统的，前几天裴老师和您这边彭老师有过交流，可能有些问题需要您这边的一些支持。
我们在集群上搭建了tratinticket系统，并且搭建了监控系统收集了日志/调用链等数据，之后我们尝试了故障注入：包括istio中的abort/delay故障，还有stress-ng注入了cpu故障。现在有几个问题想请教一下：
1.我们也尝试了stress进行内存故障的注入，但是发现如果内存指标不超过一个阈值则无效果，超过阈值则pod会杀死，所以没有效果。内存故障注入方面您这边有什么方法建议么？
2.我们还希望能够收集到更多的故障种类。看到您这边基于之前的系统实现了很多故障注入，请问一下有计划在现在的系统上复现几种吗？

**Comment by liuZOZO** [comment]
您好! 内存注入互相的原理就是如此，就是JVM的配置超过了pod中容器的配置，甚至如果单一容器可以设置为超过pod的内存配置，然后导致容器被不断kill重启，然后服务报503服务不可用。

如果只是一般的内存故障，那和常规的没有不同，会导致不断fgc，最后oom。但是我们定义的配置类故障，是服务资源配置和容器或者pod不一致导致的这一类

**Comment by liuZOZO** [comment]
故障的种类其实我们复现的故障大概就三种，异步交互，多实例，配置。您可以参看下面链接的详细描述   https://github.com/FudanSELab/train-ticket/wiki/Fault-Description

**Comment by iwtbs** [comment]
内存故障理解了～关于其他故障的问题，我想的场景是基于trainticket搭建正常系统，然后把单个pod的镜像替换成注入故障的镜像，相当于除了故障svc外其他svc不变。现在的疑惑是我之前看fault分支的代码结构和现在的trainticket有一些区别，应该没办法直接把fault里的代码打包成镜像部署，不知道基于现在的trainticket系统您这边能否也更新一下fault的版本，之后我们可以直接打包成镜像然后部署到trainticket这样。

**Comment by liuZOZO** [comment]
那个故障分支的代码确实过期了，和现在的主分支的代码以及不一致了，不能在继续使用。 不过那里有具体的故障描述，其实可以自己根据故障描述的原理，自己在正常的代码里面去复现。我们也是从工业界收集的故障描述，自己在代码里面尝试复现的。  目前我们还没有那么多的时间去重新根据新版本的代码去注册一遍故障。以后有时间会做的。
