### ISSUE TITLE
 Service 'ts-auth-service' failed to build: ADD failed

### ISSUE THREAD

**Issue by ShunyiChen** [FudanSELab/train-ticket#44]
![image](https://user-images.githubusercontent.com/12771971/65563900-b0b3f300-df7d-11e9-8922-1d8c6e9d2420.png)

**Comment by gqqnbig** [comment]
Did you fix that? How?

**Comment by gqqnbig** [comment]
It seems we have to run 

mvn -Dmaven.test.skip=true clean package
