### ISSUE TITLE
Docker-compose 部署错误

### ISSUE THREAD

**Issue by xcbula** [FudanSELab/train-ticket#47]
请问我按wiki教程部署的时候报了如下错误，是方式不对吗？
ERROR: Service 'ts-auth-service' failed to build: ADD failed: stat /var/lib/docker/tmp/docker-builder284038967/target/ts-auth-service-1.0.jar: no such file or directory

**Comment by LeBW** [comment]
目前docker compose有两种方式。
1. quick start方式，该方式无需手动构建镜像。
2. 手动构建方式。
请问您使用的哪种方式部署，以及部署时所在的目录，所使用的具体命令是如何的呢？

**Comment by xcbula** [comment]
你好，是quick start方式

命令：
git clone https://github.com/FudanSELab/train-ticket.git
cd train-ticket/
docker-compose -f quickstart-docker-compose.yml up

**Comment by LeBW** [comment]
您好，您的部署方式没有问题。我刚才用此方法重新部署了一次，没有遇到类似问题。
请确认您是否更新到最新的代码？请用git pull拉取最新代码后重新尝试一下。

**Comment by xcbula** [comment]
可以了，多谢。

**Comment by WaldenLeefx** [comment]
手动构建出错，以下第三步报错
# 1. clone the repository
git clone https://github.com/FudanSELab/train-ticket.git
cd train-ticket
# 2. build the application
mvn clean package -Dmaven.test.skip=true
# 3. build the docker images
docker-compose build

错误提示为：
WARNING: The NAMESPACE variable is not set. Defaulting to a blank string.
WARNING: The TAG variable is not set. Defaulting to a blank string.
ERROR: build path /home/lee/train-ticket/ts-ticketinfo-service either does not exist, is not accessible, or is not a valid URL.
请问是哪里出了问题？如何解决？
