### ISSUE TITLE
Which version of Kubernetes do you support? Seems like 1.16 has some problem with deploying the services.

### ISSUE THREAD

**Issue by James-QiuHaoran** [FudanSELab/train-ticket#49]
I got this error message when executing `kubectl apply -f ts-deployment-part1.yml`:

```
unable to recognize "ts-deployment-part1.yml": no matches for kind "Deployment" in version "extensions/v1beta1"
```

It seems like deprecated API issues. See `https://github.com/kubernetes/minikube/issues/5420`.

By the way, what do you mean by "Move "ts-deployment-part1.yml", "ts-deployment-part2.yml", "ts-deployment-part3.yml"."

Thank you!

**Comment by zhongyuanzhao000** [comment]
k8s 1.16 is ok，I had deployed with 1.16.
About the "move ..."  em.  I have removed it ,thanks for you advice!

**Comment by James-QiuHaoran** [comment]
> k8s 1.16 is ok，I had deployed with 1.16.
> About the "move ..." em. I have removed it ,thanks for you advice!

How do I solve this issue then?

```
unable to recognize "ts-deployment-part1.yml": no matches for kind "Deployment" in version "extensions/v1beta1"
```

Thanks
