### ISSUE TITLE
ts-preserve-service用sonarqube检测出的问题

### ISSUE THREAD

**Issue by Iam5B** [FudanSELab/train-ticket#54]
在该微服务下的FoodOrder.java和OrderTicketInfo.java所涉及的两个类中存在类方法的重复
具体来说是ts-preserve-service/src/main/java/preserve/entity/FoodOrder.java的43-73行与ts-preserve-service/src/main/java/preserve/entity/OrderTicketInfo.java的57-87行所涉及的方法定义有重复

**Comment by zhongyuanzhao000** [comment]
好的，多谢，我们之前也注意到这个问题了，会在下一版本中修复的
