### ISSUE TITLE
ts-travel-service用sonarqube检测出的问题

### ISSUE THREAD

**Issue by Iam5B** [FudanSELab/train-ticket#56]
在该微服务下也存在多处明显的代码重复情况
1. ts-travel-service/src/main/java/travel/init/InitData.java中自21行起存在大片重复
2. ts-travel-service/src/main/java/travel/entity/TravelInfo.java 的35-89行与ts-travel-service/src/main/java/travel/entity/TravelInfo.java的68-122行存在方法上的重复
3. ts-travel-service/src/main/java/travel/entity/TripInfo.java的25-48行与ts-travel-service/src/main/java/travel/entity/Trip.java 有方法上的重复

**Comment by zhongyuanzhao000** [comment]
好的，多谢，我们之前也注意到这个问题了，会在下一版本中修复的
