### ISSUE TITLE
故障注入问题

### ISSUE THREAD

**Issue by AnyuanLuo** [FudanSELab/train-ticket#60]
您好！感谢您的团队做出了如此方便的系统！我最近在做一些故障朔源的研究，看到这里有一套完整的应用及其故障注入方法就想用一下。火车票系统可以搭建成功，但是在做故障注入的时候出现了问题。我在用fault replication中的pom.xml文件创建依赖的时候出现了问题。下面是我下载安装文件的链接：
![image](https://user-images.githubusercontent.com/44501518/68279127-c0127a00-00ad-11ea-8d53-e9e17d7e9fd5.png)
下面是使用mvn clean package出错的提示，看起来好像少了些依赖包：
[ERROR] Failed to execute goal on project ts-login-service: Could not resolve dependencies for project fdse.microservice:ts-login-service:jar:1.0: The following artifacts could not be resolved: myproject.microservices:micro-service-monitoring-core:jar:1.2.2.BUILD-SNAPSHOT, myproject.microservices:micro-service-monitoring-zipkin:jar:1.2.2.BUILD-SNAPSHOT: Could not find artifact myproject.microservices:micro-service-monitoring-core:jar:1.2.2.BUILD-SNAPSHOT -> [Help 1]
然后我又在train-ticket-fault-replicate这个库中下载了其他分支的故障火车票系统的部署文件，但还是出了同样的错误。所以我想请问一下有没有一个可以正常部署故障应用的分支或者版本，我想试一下故障效果。
如果没有的话，有没有故障注入时候的源码，比如在哪些文件中写入故障代码。
期待您的回复！

**Comment by yangjiamin** [comment]
我也遇到了这个问题，请问这个问题解决了吗？可以交流下吗？我的邮箱是2013381338@qq.com。谢谢
