### ISSUE TITLE
swagger

### ISSUE THREAD

**Issue by buaazyz** [FudanSELab/train-ticket#62]
你好，请问一下，当项目通过docker-compose部署了之后，如何访问到swagg-ui的，它的url如果是ip:port/swagger-ui.html  ,但是访问不到

**Comment by flyer1212** [comment]
when use docker-compose：

# for example :  ts-order-service ， your port should be the target service port: 
http://ip:12031/swagger-ui.html#/

![image](https://user-images.githubusercontent.com/18101769/68735429-8f37c500-0618-11ea-8f47-593154622e4c.png)

**Comment by buaazyz** [comment]
> when use docker-compose：
> 
> # for example : ts-order-service ， your port should be the target service port:
> http://ip:12031/swagger-ui.html#/
> 
> ![image](https://user-images.githubusercontent.com/18101769/68735429-8f37c500-0618-11ea-8f47-593154622e4c.png)

**thank you so much**
