### ISSUE TITLE
大流量注入后的查询异常

### ISSUE THREAD

**Issue by CZacker** [FudanSELab/train-ticket#97]
### Summary
正常流量下（单用户点击）的操作，可以查询出票务列表，在一段时间的大流量操作后，routeID出现混乱，到这无法正常查询票务（恢复流量后，也无法查询）。

Before error：
![image](https://user-images.githubusercontent.com/25023285/72312383-ef072680-36c2-11ea-98f4-a8dbab347778.png)
After error：
![image](https://user-images.githubusercontent.com/25023285/72312960-bbc59700-36c4-11ea-8473-5faffa89808e.png)

### Steps to reproduce 
istio -> quick-deployment-k8s -> add user -> bots inject

### Environment

NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

docker version:  18.09.6
ts-travel-service version: 0.0.3

 
Kubernetes version:
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

istio version: 
client version: 1.4.0
control plane version: 1.4.0
data plane version: 1.4.0 (129 proxies)

### Search result

ts-travel -service log:
![image](https://user-images.githubusercontent.com/25023285/72312915-96d12400-36c4-11ea-9a48-461b71439873.png)

ts-route-mongo collection:
![image](https://user-images.githubusercontent.com/25023285/72312899-8caf2580-36c4-11ea-8cea-b6a48bf6f622.png)

error shooting :
![image](https://user-images.githubusercontent.com/25023285/72312943-afd9d500-36c4-11ea-8e52-366443262a6e.png)
![image](https://user-images.githubusercontent.com/25023285/72312951-b36d5c00-36c4-11ea-9cbb-c4434ed8fd67.png)

**Comment by CZacker** [comment]
![image](https://user-images.githubusercontent.com/25023285/72314273-3bedfb80-36c9-11ea-84db-9fe4c58a60e1.png)
具体日志输出

**Comment by zhongyuanzhao000** [comment]
你好，
       日志中提到的这个routeId: `92708982-77af-4318-be25-57ccb0ff69ad`是route service服务初始化时就被写入对应mongo的，如果出现这种 `No content with the routeId` 的提示(也即mongo不存在这个本应存在的信息)，说明大流量操作的情况下数据库已出现了问题，比如mongo发生了重启进而丢失了该routeId对应的信息等。
       建议增大 `ts-route-mongo` 这个Deployment资源的cpu/内存试试。

**Comment by CZacker** [comment]
ok，还有一个问题同样一个查询接口，在已经把服务资源提升之后的余票查询还会出现如下结果，这个是什么原因呢？具体服务日志需要复现后
![image](https://user-images.githubusercontent.com/25023285/72427267-58bc2900-37c6-11ea-950d-31288be1de5b.png)

**Comment by CZacker** [comment]
![image](https://user-images.githubusercontent.com/25023285/73604545-74e50600-45cd-11ea-81a5-831f467603ba.png)
