### ISSUE TITLE
使用docker-compose在server上编译的问题

### ISSUE THREAD

**Issue by QuanQuanoooooo** [FudanSELab/train-ticket#99]
我在编译您的benchmark中出现了一些问题。
操作如下：
$ sudo docker-compose -f deployment/quickstart-docker-compose/quickstart-docker-compose.yml up
WARNING: Some services (jaeger, ts-admin-route-service, ts-admin-travel-service, ts-admin-user-service) use the 'deploy' key, which will be ignored. Compose does not support 'deploy' configuration - use `docker stack deploy` to deploy to a swarm.
Starting quickstart-docker-compose_redis_1 ... 
Starting quickstart-docker-compose_ts-execute-service_1                   ... 
Starting quickstart-docker-compose_redis_1                                ... done
Starting quickstart-docker-compose_ts-route-plan-service_1                ... done
Starting quickstart-docker-compose_ts-auth-service_1        ... 
Starting quickstart-docker-compose_ts-rebook-service_1                    ... done
Starting quickstart-docker-compose_ts-news-service_1        ... 
Starting quickstart-docker-compose_ts-order-other-mongo_1                 ... done
Starting quickstart-docker-compose_ts-consign-price-mongo_1               ... done
Recreating quickstart-docker-compose_ts-contacts-service_1  ... 
Recreating quickstart-docker-compose_ts-admin-route-service_1             ... done
Starting quickstart-docker-compose_ts-order-mongo_1                           ... done
Starting quickstart-docker-compose_ts-inside-payment-mongo_1                  ... 
Starting quickstart-docker-compose_ts-travel-plan-service_1                   ... done
Starting quickstart-docker-compose_ts-admin-order-service_1                   ... 
Starting d3d2ff4d0f66_quickstart-docker-compose_ts-security-service_1         ... done
Starting quickstart-docker-compose_ts-payment-service_1                   ... done
Starting quickstart-docker-compose_ts-admin-user-service_1                    ... done
Recreating quickstart-docker-compose_ts-user-service_1                        ... done
Starting quickstart-docker-compose_ts-food-map-service_1                      ... done
Starting quickstart-docker-compose_ts-notification-service_1  ... 
Starting quickstart-docker-compose_ts-train-service_1                         ... done
Starting quickstart-docker-compose_ts-auth-mongo_1            ... 
Starting d3d2ff4d0f66_quickstart-docker-compose_ts-security-service_1 ... 
Starting quickstart-docker-compose_ts-verification-code-service_1             ... done
Starting quickstart-docker-compose_ts-config-mongo_1          ... 
Starting quickstart-docker-compose_ts-voucher-mysql_1                         ... done
Starting quickstart-docker-compose_ts-preserve-other-service_1                ... done
Starting quickstart-docker-compose_ts-food-map-mongo_1                        ... done
Starting quickstart-docker-compose_ts-order-other-service_1                   ... 
Starting quickstart-docker-compose_ts-execute-service_1                       ... done
Starting quickstart-docker-compose_ts-seat-service_1                          ... done
Starting quickstart-docker-compose_ts-order-service_1                         ... done
Starting quickstart-docker-compose_ts-inside-payment-service_1                ... done
Starting quickstart-docker-compose_ts-ticket-office-mongo_1                   ... done
Starting quickstart-docker-compose_ts-assurance-mongo_1                       ... done
Starting quickstart-docker-compose_ts-food-mongo_1                            ... done
Starting quickstart-docker-compose_ts-ticket-office-mongo_1               ... 
Starting quickstart-docker-compose_ts-assurance-service_1                     ... done
Recreating quickstart-docker-compose_ts-consign-service_1                     ... done
Starting 30890d25147a_quickstart-docker-compose_ts-admin-basic-info-service_1 ... done
Starting quickstart-docker-compose_ts-basic-service_1                         ... done
Starting quickstart-docker-compose_ts-travel2-service_1                       ... done
Starting quickstart-docker-compose_ts-consign-mongo_1                         ... done
Recreating quickstart-docker-compose_ts-ui-dashboard_1                        ... done
Starting quickstart-docker-compose_ts-inside-payment-mongo_1                  ... done
Starting quickstart-docker-compose_ts-order-other-service_1                   ... done
Starting quickstart-docker-compose_ts-price-mongo_1                           ... done
Starting quickstart-docker-compose_ts-route-service_1                         ... done
Starting quickstart-docker-compose_ts-news-mongo_1                            ... done
Starting quickstart-docker-compose_ts-admin-order-service_1                   ... done
Starting quickstart-docker-compose_ts-ticket-office-service_1                 ... done
Starting quickstart-docker-compose_ts-station-mongo_1                         ... done
Starting quickstart-docker-compose_ts-travel-service_1                        ... done
Starting quickstart-docker-compose_ts-payment-mongo_1                         ... done
Starting quickstart-docker-compose_ts-travel2-mongo_1                         ... done
Starting quickstart-docker-compose_ts-voucher-service_1                       ... done
Attaching to quickstart-docker-compose_ts-route-plan-service_1, quickstart-docker-compose_ts-consign-price-mongo_1, quickstart-docker-compose_ts-station-service_1, quickstart-docker-compose_ts-price-service_1, quickstart-docker-compose_redis_1, quickstart-docker-compose_ts-admin-route-service_1, quickstart-docker-compose_ts-preserve-service_1, quickstart-docker-compose_jaeger_1, quickstart-docker-compose_ts-payment-service_1, quickstart-docker-compose_ts-rebook-service_1, quickstart-docker-compose_ts-account-mongo_1, quickstart-docker-compose_ts-order-other-mongo_1, quickstart-docker-compose_ts-contacts-mongo_1, quickstart-docker-compose_ts-route-mongo_1, quickstart-docker-compose_ts-order-mongo_1, quickstart-docker-compose_ts-travel-plan-service_1, af7f5774706d_quickstart-docker-compose_ts-config-service_1, b473547a7bd0_quickstart-docker-compose_ts-admin-travel-service_1, quickstart-docker-compose_ts-auth-service_1, d3d2ff4d0f66_quickstart-docker-compose_ts-security-service_1, quickstart-docker-compose_ts-train-mongo_1, quickstart-docker-compose_ts-config-mongo_1, quickstart-docker-compose_ts-consign-price-service_1, quickstart-docker-compose_ts-train-service_1, quickstart-docker-compose_ts-voucher-mysql_1, quickstart-docker-compose_ts-rebook-mongo_1, quickstart-docker-compose_ts-notification-service_1, quickstart-docker-compose_ts-auth-mongo_1, quickstart-docker-compose_ts-contacts-service_1, quickstart-docker-compose_ts-admin-user-service_1, quickstart-docker-compose_ts-verification-code-service_1, quickstart-docker-compose_ts-inside-payment-mongo_1, quickstart-docker-compose_ts-news-service_1, quickstart-docker-compose_ts-user-service_1, quickstart-docker-compose_ts-food-service_1, quickstart-docker-compose_ts-user-mongo_1, quickstart-docker-compose_ts-travel-mongo_1, quickstart-docker-compose_ts-food-map-mongo_1, quickstart-docker-compose_ts-security-mongo_1, quickstart-docker-compose_ts-ticketinfo-service_1, quickstart-docker-compose_ts-cancel-service_1, quickstart-docker-compose_ts-preserve-other-service_1, quickstart-docker-compose_ts-inside-payment-service_1, 30890d25147a_quickstart-docker-compose_ts-admin-basic-info-service_1, quickstart-docker-compose_ts-consign-mongo_1, quickstart-docker-compose_ts-ticket-office-service_1, quickstart-docker-compose_ts-news-mongo_1, quickstart-docker-compose_ts-execute-service_1, quickstart-docker-compose_ts-order-service_1, quickstart-docker-compose_ts-ticket-office-mongo_1, quickstart-docker-compose_ts-route-service_1, quickstart-docker-compose_ts-station-mongo_1, quickstart-docker-compose_ts-travel2-service_1, quickstart-docker-compose_ts-payment-mongo_1, quickstart-docker-compose_ts-seat-service_1, quickstart-docker-compose_ts-travel2-mongo_1, quickstart-docker-compose_ts-basic-service_1, quickstart-docker-compose_ts-admin-order-service_1, quickstart-docker-compose_ts-ui-dashboard_1, quickstart-docker-compose_ts-price-mongo_1, quickstart-docker-compose_ts-consign-service_1, quickstart-docker-compose_ts-travel-service_1, quickstart-docker-compose_ts-food-map-service_1, quickstart-docker-compose_ts-voucher-service_1, quickstart-docker-compose_ts-order-other-service_1, quickstart-docker-compose_ts-assurance-mongo_1, quickstart-docker-compose_ts-food-mongo_1, quickstart-docker-compose_ts-assurance-service_1

但是我在无法打开server.ip:8080下的网站，请问可能是什么原因呢

**Comment by QuanQuanoooooo** [comment]
完整版的终端输出在：
https://drive.google.com/open?id=1MQ-mVHEZv9SSrwQ_HVJLKla2TlGEQ3e9
谢谢！

**Comment by LeBW** [comment]
从终端输出中没有看出明显的问题。
建议先查看`ts-ui-dashboard`这个容器运行是否正常。

**Comment by QuanQuanoooooo** [comment]
您好。
我只进行了deployment/quickstart-docker-compose/quickstart-docker-compose.yml中
ts-ui-dashboard:
image: codewisdom/ts-ui-dashboard:0.0.3
restart: always
ports:
- 40090:40090
networks:
- my-network
这一部分的修改
一直无法在浏览器打开ui界面
我的container 信息如下：
https://drive.google.com/file/d/1HRWF_-6K_6N7o5EE2E7MzYEjAhBd_cRC/view?usp=sharing
其中ts-ui-dashboard的具体信息如下：
https://drive.google.com/file/d/1X9mVEp5UxEETsEP16ZERUSsSunR6T6U7/view?usp=sharing

**Comment by QuanQuanoooooo** [comment]
> 从终端输出中没有看出明显的问题。
> 建议先查看`ts-ui-dashboard`这个容器运行是否正常。
